name: icon-automation
on:
  push:
    branches:
      - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - package.json

jobs:
  icon_automation:
    name: figma icon automation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: yarn install
      - name: Figma Action
        uses: primer/figma-action@v1.0.0-alpha.2
        with:
          args: "format=svg outputDir=./src/"
        env:
          FIGMA_FILE_URL: https://www.figma.com/file/22YpQpwQKSlLXPaud4TgrO/Untitled
          FIGMA_TOKEN: 259941-1f6cf16d-49e9-4b59-8d89-5e5d7a70709e
      - run: yarn generate
      - run: yarn build:bundle
      # - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
      # - run: yarn publish
      # env:
      # NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - run: yarn build
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: 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
